export type Problem = {
	id: string;
	title: string;
	difficulty: string;
	category: string;
	order: number;
	videoId?: string;
};

export const problems: Problem[] = [
		//id is the name of the page when we click on it.
	{	
		id: "1",
		title: "Hello, World!",
		difficulty: "Easy",
		category: "",
		order: 1,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "2",
		title: "Print Full Name",
		difficulty: "Easy",
		category: "",
		order: 2,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "3",
		title: "Variables and Operations",
		difficulty: "Easy",
		category: "",
		order: 3,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "4",
		title: "Even or Odd",
		difficulty: "Easy",
		category: "",
		order: 4,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "5",
		title: "Simple Sum",
		difficulty: "Easy",
		category: "",
		order: 5,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "6",
		title: "Check if a Number is Positive, Negative, or Zero",
		difficulty: "Medium",
		category: "",
		order: 6,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "7",
		title: "LeapYear",
		difficulty: "Medium",
		category: "",
		order: 7,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "8",
		title: "Print Numbers from 1 to N",
		difficulty: "Medium",
		category: "",
		order: 8,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "9",
		title: "Find the Maximum",
		difficulty: "Medium",
		category: "",
		order: 9,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "10",
		title: "Count Vowels",
		difficulty: "Medium",
		category: "",
		order: 10,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "11",
		title: "Calculate the Sum of Even Numbers from 1 to N",
		difficulty: "Medium",
		category: "",
		order: 11,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "12",
		title: "Reverse String",
		difficulty: "Medium",
		category: "",
		order: 12,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "13",
		title: "Find the Sum of Digits of a Number",
		difficulty: "Hard",
		category: "",
		order: 13,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "14",
		title: "Check for Prime Number",
		difficulty: "Hard",
		category: "",
		order: 14,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "15",
		title: "Count Occurrences of a Character in a String",
		difficulty: "Hard",
		category: "",
		order: 15,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "16",
		title: "Find the Second Largest Number in an Array",
		difficulty: "Hard",
		category: "",
		order: 16,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "17",
		title: "Check for Armstrong Number",
		difficulty: "Hard",
		category: "",
		order: 17,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "18",
		title: "Reverse an Array",
		difficulty: "Hard",
		category: "",
		order: 18,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "19",
		title: "Find the Average of an Array",
		difficulty: "Hard",
		category: "",
		order: 19,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "20",
		title: "Remove Duplicates from an Array",
		difficulty: "Hard",
		category: "",
		order: 20,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "21",
		title: "Find the Longest Word in a Sentence",
		difficulty: "Hard",
		category: "",
		order: 21,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "22",
		title: "Find the GCD (Greatest Common Divisor) of Two Numbers",
		difficulty: "Hard",
		category: "",
		order: 22,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "23",
		title: "Calculate Power of a Number",
		difficulty: "Hard",
		category: "",
		order: 23,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "24",
		title: "Sum of Even Numbers",
		difficulty: "Hard",
		category: "",
		order: 24,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "25",
		title: "Check for Perfect Number",
		difficulty: "Hard",
		category: "",
		order: 25,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "14",
		title: "",
		difficulty: "Hard",
		category: "",
		order: 14,
		videoId: "xvFZjo5PgG0",
	},
	{
		id: "two-sum",
		title: "two-sum",
		difficulty: "Hard",
		category: "",
		order: 100,
		videoId: "xvFZjo5PgG0",
	},
];